details:
  namespace: student15-bookinfo-uat
  image: ghcr.io/konlawatit/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student15/details(/|$)(.*)"
  serviceType: ClusterIP
