apiVersion: v1
description: Bookinfo Details Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: http://itkmitl.bookinfo.dev.opsta.net/student15/details
maintainers:
  - name: student15
    email: 62070007@it.kmitl.ac.th
sources:
  - https://github.com/konlawatit/itkmitl-bookinfo-details
